### ISSUE TITLE
Question Start not working.

### ISSUE THREAD

**Issue by DarkDaniel107** [theusaf/KahootPY#3]
So I did the example you did for the How do I submit my answer. It wouldn't answer. I added a print statement inside the questionStartHandle, and nothing got printed when the question started. Any idea how to fix it?

**Comment by theusaf** [comment]
This is an issue that I will be fixing soon.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
