### ISSUE TITLE
Might want to consider revising the challengehandler.

### ISSUE THREAD

**Issue by michaelshumshum** [theusaf/KahootPY#9]
This is only. applicable to kahoot-py since we have to evaluate javascript using python. Instead of converting the javascript into python, we could instead just extract the necessary information from the javascript. Your method requires two very long functions is quite unreliable. 

You may want to refer to [this repository](https://github.com/msemple1111/kahoot-hack). I fixed their challenge solver using the concept above as I noticed that the only changes they make in the challenge is the variables `offset` and `message`, one being a plain string and the other just an expression that can be evaluated. For the rest, don't bother converting it to python and only extract the unique variables. 

Also, the `concatTokens` function doesn't seem to work.

**Comment by michaelshumshum** [comment]
Note that I based my fix for msemple111's kahoot-hack from your notes [here](https://kahoot.js.org/ex/decode-client).

**Comment by theusaf** [comment]
Thanks! I’ll check it out.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
